import com.google.gson.Gson;
import org.jfree.ui.RefineryUtilities;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.*;
import java.util.*;

/**
 * Created by Ayush Bandil on 15/11/2019.
 */

public class Main {
    private static String from = "";
    private static String to = "";
    public static String area = "Perth";
    private static ArrayList<Coordinates> bingCoordinates;
    private static ArrayList<Coordinates> osmCoordinates;
    private static ArrayList<Coordinates> googleCoordinates;




    public static void main(String[] args) {
        //generating all coordinates (look in the databse for the area variable's existing coordinates)
        ArrayList<Coordinates> areaCoordinates = generateAreaCoordinates(); //this puts the coordinates in an arraylist

        for (int runCount = 0; runCount < PropertiesReader.getInt("noOfRuns"); runCount++) {
            System.out.println("Processing " + (runCount + 1) + " route in " + area);
            try {
                processOneRoute(areaCoordinates); //processing one route
            } catch (Exception e){
                System.out.println("Could not process " + runCount + "th count");
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException e1) {
                    e1.printStackTrace();
                }
            }
        }
    }

    private static void processOneRoute(ArrayList<Coordinates> areaCoordinates) {
        Coordinates fromCor = null;
        Coordinates toCor = null;

        while (fromCor == null
//                || fromCor.getRouteId() != 0
                )
        {
            fromCor = areaCoordinates.get((int) (Math.random() * areaCoordinates.size()));
            from = fromCor.convertToString();
            //what is happening here; we are picking one point at random from the arraylist
        }

        while (toCor == null
//                || toCor.getRouteId() != 0
                || to.equals(from)
                //this is making sure that the 2 points chosen are at least 5km appart
                || getDist(fromCor, toCor) < PropertiesReader.getInt("fromToMinDist"))

        {
            toCor = areaCoordinates.get((int) (Math.random() * areaCoordinates.size()));
            to = toCor.convertToString();
        }

        //up to this point what we did is: picked 2 points that have priority # null and that are at least 5km apart, and converted them to a string
        System.out.println("   From " + from + ", to " + to);

        // Processing Bing: we are calling bing maps api that returns all points in the given route, storing them in an arraylist
        {
            String bingURL = getBingURL();
            String json = getJsonResponse(bingURL);
            Gson gson = new Gson();
            BingApiResponse response = gson.fromJson(json, BingApiResponse.class);
            bingCoordinates = response.getBingCoordinates();
        }

//        for (int i = 0; i < bingCoordinates.size(); i++) {
//            System.out.println(bingCoordinates.get(i).getLat() + ", " + bingCoordinates.get(i).getLon());
//        }

        // Processing OSM: similiar but with osm, storing them in an arraylist
        {
            String osmURL = getOsmURL();
            String json = getJsonResponse(osmURL);
            Gson gson = new Gson();
            OsmApiResponse response = gson.fromJson(json, OsmApiResponse.class);
            osmCoordinates = response.getOsmCoordinates();
        }

        // Process Google Maps
        {
            JavaRequestMessage jrm = new JavaRequestMessage();
            jrm.setOutputFormat(OutputFormats.json);
            List<Coordinates> route = new ArrayList<>();
            route.add(bingCoordinates.get(0));
            route.add(bingCoordinates.get(bingCoordinates.size() - 1));
            Collection<ToAvoidGM> avoid = new ArrayList<>();
            avoid.add(ToAvoidGM.tolls);
            jrm.setAvoid(avoid);
            jrm.setRouteCoords(route);
            String request = jrm.generateGRequest();
            googleCoordinates = jrm.parseJson(jrm.getJsonResponse(request));
        }
//        generateGraph();

        //go to imnmplementation for explanation
        insertNewCordinates(areaCoordinates);


        Analysis.doAnalysis(bingCoordinates, osmCoordinates);
    }

    private static double getDist(Coordinates fromCor, Coordinates toCor) {
        String disQuery = PropertiesReader.getString("disQuery");
        disQuery = disQuery.replace("<POINT1_COR>", fromCor.getLon() + " " + fromCor.getLat());
        disQuery = disQuery.replace("<POINT2_COR>", toCor.getLon() + " " + toCor.getLat());
        Double dist = ConnectionUtils.executeJdbcSingleOutputQuery(disQuery);
        return dist;
    }

    //this will update the area`coordinates arraylist to include all new points generated by bing and osm. It will then
    //add these new points to the DB table from which it originally got populated from (areaCoordinates arraylist0
    private static void insertNewCordinates(ArrayList<Coordinates> areaCoordinates) {
        Connection con = ConnectionUtils.getConnection();
        final int[] count = {0};

        //adding bing points
        bingCoordinates.forEach(cor -> {
            if (!areaCoordinates.contains(cor)) {
                insertCoordinate(cor.getLat(), cor.getLon(), con);
                areaCoordinates.add(cor);
                count[0]++;
            }
        });

        //adding osm points
        osmCoordinates.forEach(cor -> {
            if (!areaCoordinates.contains(cor)) {
                insertCoordinate(cor.getLat(), cor.getLon(), con);
                areaCoordinates.add(cor);
                count[0]++;
            }
        });

        try {
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.out.println("   Sucessfully inserted " + count[0] + " new coordinates in " + area);
    }

    private static void insertCoordinate(double lat, double lon, Connection con) {
        String query = "INSERT INTO COORDINATES" +
                "([CITY]\n" +
                ",[Lat]\n" +
                ",[Long]\n" +
                ",[Priority])\n" +
                "VALUES\n" +
                "('" + area +
                "'," + lat +
                "," + lon +
                "," + 1 + ")";

        ConnectionUtils.executeJdbcQuery(query);
    }

    private static void generateGraph() {
        final XYPlotter demo = new XYPlotter("Ayush", bingCoordinates, osmCoordinates);
        demo.pack();
        RefineryUtilities.centerFrameOnScreen(demo);
        demo.setVisible(true);
    }

    private static String getBingURL() {
        BingRequestMessage message = new BingRequestMessage();
        Collection<String> wps = new ArrayList<>();
        wps.add(from);
        wps.add(to);
        message.setWayPoints(wps);

        Collection<ToAvoid> avoid = new ArrayList<>();
        avoid.add(ToAvoid.minimizeTolls);
        message.setAvoid(avoid);

        return message.generateRequest();
    }

    private static String getOsmURL() {
        OsmRequestMessage message = new OsmRequestMessage();
        message.setFrom(bingCoordinates.get(0));
        message.setTo(bingCoordinates.get(bingCoordinates.size() - 1));
        return message.generateRequest();
    }

    private static String getJsonResponse(String urlStr) {
        URL url = null;
        BufferedReader reader = null;
        StringBuilder stringBuilder = null;
        try {
            url = new URL(urlStr);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HttpURLConnection connection = null;
        try {
            connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");
            connection.setReadTimeout(15 * 1000);
            connection.connect();

            // read the output from the server
            reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            stringBuilder = new StringBuilder();

            String line = null;
            while ((line = reader.readLine()) != null) {
                stringBuilder.append(line + "\n");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return stringBuilder.toString();
    }


    private static String appendParem(String target, String param) {
        return target + "&" + param;
    }

    public static ArrayList<Coordinates> generateAreaCoordinates() {
        Connection con = ConnectionUtils.getConnection(); //connecting to MS DB
        ArrayList<Coordinates> areaCoordinates = new ArrayList<>();
        PreparedStatement ps = null;
        double lat = 0f;
        double lon = 0f;
        int routeId = 0;

        try {
            ps = con.prepareStatement("select * from COORDINATES where CITY = '" + area + "';"); //running querry
            ResultSet rs = ps.executeQuery();
            while (rs.next()) { //retrieve result set and putting them into an arraylist
                lat = rs.getDouble("Lat");
                lon = rs.getDouble("Long");
                routeId = rs.getInt("Priority");
                areaCoordinates.add(new Coordinates(lat, lon, routeId));
            }
            rs.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return areaCoordinates;
    }
}
